name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'ags/widget/utils/config/configSchema.ts'
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'mkdocs.yml'

permissions:
  contents: write  # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript
        run: tsc

      - name: Generate config documentation
        run: node scripts/build/generateConfigDocs.js

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force